# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    parameter_name: value

services:
    kiskis_factory:
      class: SandboxBundle\Service\KiskisFactory
      tags:
       - { name: doctrine.event_listener, event: prePersist }
       - { name: doctrine.event_subscriber, event: postPersist }

    #kiskis:
    # class: SandboxBundle\Service\Kiskis

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
