<?php

namespace SandboxBundle\Repository;

/**
 * KiskisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KiskisRepository extends \Doctrine\ORM\EntityRepository
{
}
